require("dotenv").config();

const fs = require("fs");
const path = require("path");
const { Pool } = require("pg");

let pool;

function getPool() {
  if (pool) return pool;

  if (!process.env.DATABASE_URL) {
    throw new Error("DATABASE_URL is not set");
  }

  pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false },
  });

  return pool;
}

function normalizeJson(value, fallback = null) {
  if (value === undefined || value === null) return fallback;
  if (typeof value === "string") {
    try {
      return JSON.parse(value);
    } catch {
      return fallback;
    }
  }
  return value;
}

function nullable(value) {
  return value === "" || value === undefined ? null : value;
}

async function migrate() {
  const db = getPool();

  await db.query(`
    CREATE TABLE IF NOT EXISTS schema_migrations (
      id integer generated by default as identity primary key,
      filename varchar(191) not null unique,
      applied_at timestamptz not null default now()
    )
  `);

  const schemaPath = path.join(
    __dirname,
    "..",
    "database",
    "supabase",
    "001_schema.sql"
  );

  if (!fs.existsSync(schemaPath)) {
    throw new Error(`PostgreSQL schema not found: ${schemaPath}`);
  }

  const schema = fs.readFileSync(schemaPath, "utf8");

  await db.query(schema);

  return true;
}

async function queryRows(table) {
  const { rows } = await getPool().query(`SELECT * FROM ${table}`);
  return rows;
}

async function loadDb(createEmptyDb) {
  const db = createEmptyDb();

  const [
    users,
    customers,
    products,
    variants,
    costHistory,
    suppliers,
    cargoBatches,
    orders,
    orderItems,
    timelines,
    statusHistory,
    payments,
    refunds,
    returns,
    returnItems,
    cargoItems,
    expenses,
    inventoryTransactions,
    auditLogs,
    dismissedNotifications,
    settings,
  ] = await Promise.all([
    queryRows("users"),
    queryRows("customers"),
    queryRows("products"),
    queryRows("product_variants"),
    queryRows("product_cost_history"),
    queryRows("suppliers"),
    queryRows("cargo_batches"),
    queryRows("orders"),
    queryRows("order_items"),
    queryRows("order_timeline"),
    queryRows("order_status_history"),
    queryRows("payments"),
    queryRows("refunds"),
    queryRows("returns"),
    queryRows("return_items"),
    queryRows("cargo_items"),
    queryRows("expenses"),
    queryRows("inventory_transactions"),
    queryRows("audit_logs"),
    queryRows("dismissed_notifications"),
    queryRows("settings"),
  ]);

  db.users = users.map((r) => ({
    id: r.id,
    name: r.name,
    email: r.email,
    passwordHash: r.password_hash,
    role: r.role,
    active: r.status === "active",
    permissions: normalizeJson(r.permissions, {}),
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  }));

  db.customers = customers.map((r) => ({
    id: r.id,
    customerCode: r.customer_code,
    name: r.name,
    phone: r.phone,
    email: r.email,
    contact: r.contact,
    address: r.address,
    township: r.township,
    deliveryMethod: r.delivery_method || "Deli",
    notes: r.notes,
    customerVisibleNotes: r.customer_visible_notes,
    internalNotes: r.internal_notes,
    tags: normalizeJson(r.tags, []),
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  }));

  const costByProduct = new Map();

  for (const row of costHistory) {
    if (!costByProduct.has(row.product_id)) {
      costByProduct.set(row.product_id, []);
    }

    costByProduct.get(row.product_id).push({
      id: row.id,
      cost: Number(row.cost || 0),
      date: row.cost_date,
      note: row.note,
      createdAt: row.created_at,
    });
  }

  const variantsByProduct = new Map();

  for (const row of variants) {
    if (!variantsByProduct.has(row.product_id)) {
      variantsByProduct.set(row.product_id, []);
    }

    variantsByProduct.get(row.product_id).push({
      id: row.id,
      productId: row.product_id,
      sku: row.sku,
      size: row.size,
      color: row.color,
      costPrice: Number(row.cost_price || 0),
      sellingPrice: Number(row.selling_price || 0),
      stockQuantity: Number(row.stock_quantity || 0),
      reservedQuantity: Number(row.reserved_quantity || 0),
      soldQuantity: Number(row.sold_quantity || 0),
      returnedQuantity: Number(row.returned_quantity || 0),
      damagedQuantity: Number(row.damaged_quantity || 0),
      lowStockThreshold: Number(row.low_stock_threshold || 0),
      status: row.status,
      createdAt: row.created_at,
      updatedAt: row.updated_at,
    });
  }

  db.products = products.map((r) => ({
    id: r.id,
    productCode: r.product_code,
    sku: r.sku,
    name: r.name,
    description: r.description,
    category: r.category,
    supplier: r.supplier,
    productType: r.product_type,
    costPrice: Number(r.cost_price || 0),
    sellingPrice: Number(r.selling_price || 0),
    discountPrice: Number(r.discount_price || 0),
    supplierLink: r.supplier_link,
    supplierProductCode: r.supplier_product_code,
    supplierPrice: Number(r.supplier_price || 0),
    estimatedProductCost: Number(r.estimated_product_cost || 0),
    defaultWaitingTime: r.default_waiting_time,
    defaultCargoCost: Number(r.default_cargo_cost || 0),
    customerDescription: r.customer_description,
    notes: r.notes,
    internalNotes: r.internal_notes,
    availableSizes: normalizeJson(r.available_sizes, []),
    availableColors: normalizeJson(r.available_colors, []),
    images: normalizeJson(r.images, []),
    status: r.status,
    variants: variantsByProduct.get(r.id) || [],
    costHistory: costByProduct.get(r.id) || [],
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  }));

  db.suppliers = suppliers.map((r) => ({
    id: r.id,
    name: r.name,
    platform: r.platform,
    supplierLink: r.supplier_link,
    contact: r.contact,
    note: r.note,
    productCost: Number(r.product_cost || 0),
    supplierStatus: r.supplier_status,
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  }));

  const cargoItemsByBatch = new Map();

  for (const row of cargoItems) {
    if (!cargoItemsByBatch.has(row.cargo_batch_id)) {
      cargoItemsByBatch.set(row.cargo_batch_id, []);
    }

    cargoItemsByBatch.get(row.cargo_batch_id).push(row);
  }

  db.cargoBatches = cargoBatches.map((r) => {
    const items = cargoItemsByBatch.get(r.id) || [];

    return {
      id: r.id,
      batchId: r.batch_id,
      route: r.route,
      cargoFee: Number(r.cargo_fee || 0),
      chinaMuseCargoFee: Number(r.china_muse_cargo_fee || 0),
      museYangonCargoFee: Number(r.muse_yangon_cargo_fee || 0),
      otherExpenses: Number(r.other_expenses || 0),
      status: r.status,
      batchDate: r.batch_date,
      arrivalDate: r.arrival_date,
      notes: r.notes,
      orderIds: [...new Set(items.map((x) => x.order_id).filter(Boolean))],
      productIds: [...new Set(items.map((x) => x.product_id).filter(Boolean))],
      createdAt: r.created_at,
      updatedAt: r.updated_at,
    };
  });

  const itemsByOrder = new Map();

  for (const row of orderItems) {
    if (!itemsByOrder.has(row.order_id)) {
      itemsByOrder.set(row.order_id, []);
    }

    itemsByOrder.get(row.order_id).push({
      id: row.id,
      productId: row.product_id,
      variantId: row.variant_id,
      productName: row.product_name_snapshot,
      sku: row.sku,
      size: row.size,
      color: row.color,
      quantity: Number(row.quantity || 0),
      unitPrice: Number(row.unit_price || 0),
      purchaseCost: Number(row.cost_price || 0),
      cargoCost: Number(row.cargo_cost || 0),
      discount: Number(row.discount || 0),
      subtotal: Number(row.subtotal || 0),
      supplierStatus: row.supplier_status,
      cargoStatus: row.cargo_status,
      arrivalStatus: row.arrival_status,
      expectedArrival: row.expected_arrival,
      batchId: row.batch_id,
      customerNotified: row.customer_notified,
      createdAt: row.created_at,
    });
  }

  const paymentsByOrder = new Map();

  for (const row of payments) {
    if (!paymentsByOrder.has(row.order_id)) {
      paymentsByOrder.set(row.order_id, []);
    }

    paymentsByOrder.get(row.order_id).push({
      id: row.id,
      orderId: row.order_id,
      customerId: row.customer_id,
      amount: Number(row.amount || 0),
      paymentMethod: row.payment_method,
      paymentType: row.payment_type,
      paymentDate: row.payment_date,
      reference: row.reference,
      receivedBy: row.received_by,
      receivedByName: row.received_by_name,
      notes: row.notes,
      createdAt: row.created_at,
    });
  }

  const refundsByOrder = new Map();

  for (const row of refunds) {
    if (!refundsByOrder.has(row.order_id)) {
      refundsByOrder.set(row.order_id, []);
    }

    refundsByOrder.get(row.order_id).push({
      id: row.id,
      orderId: row.order_id,
      customerId: row.customer_id,
      amount: Number(row.amount || 0),
      method: row.method,
      reason: row.reason,
      refundDate: row.refund_date,
      processedBy: row.processed_by,
      processedByName: row.processed_by_name,
      createdAt: row.created_at,
    });
  }

  db.payments = payments.map((row) => ({
    id: row.id,
    orderId: row.order_id,
    customerId: row.customer_id,
    amount: Number(row.amount || 0),
    paymentMethod: row.payment_method,
    paymentType: row.payment_type,
    paymentDate: row.payment_date,
    reference: row.reference,
    receivedBy: row.received_by,
    receivedByName: row.received_by_name,
    notes: row.notes,
    createdAt: row.created_at,
  }));

  db.orders = orders.map((r) => ({
    id: r.id,
    orderNumber: r.order_number,
    customerId: r.customer_id,
    createdBy: r.created_by,
    orderType: r.order_type,
    orderDate: r.order_date,
    status: r.status,
    preorderStatus: r.preorder_status,
    packingStatus: r.packing_status,
    deliveryStatus: r.delivery_status,
    deliveryMethod: r.delivery_method,
    trackingNumber: r.tracking_number,
    waitingTime: r.waiting_time,
    expectedArrival: r.expected_arrival,
    batchId: r.batch_id,
    customerNotified: r.customer_notified,
    customerNotes: r.customer_notes,
    internalNotes: r.internal_notes,
    stockState: r.stock_state,
    subtotal: Number(r.subtotal || 0),
    discount: Number(r.discount || 0),
    deliveryFee: Number(r.delivery_fee || 0),
    shopDeliveryCost: Number(r.shop_delivery_cost || 0),
    allocatedExpense: Number(r.allocated_expense || 0),
    total: Number(r.total || 0),
    paidAmount: Number(r.paid_amount || 0),
    refundedAmount: Number(r.refunded_amount || 0),
    finalPaidAmount: Number(r.final_paid_amount || 0),
    balance: Number(r.balance || 0),
    requiredDeposit: Number(r.required_deposit || 0),
    productCost: Number(r.product_cost || 0),
    cargoCost: Number(r.cargo_cost || 0),
    netProfit: Number(r.net_profit || 0),
    paymentStatus: r.payment_status,
    packedBy: r.packed_by,
    packedByName: r.packed_by_name,
    packedAt: r.packed_at,
    cancellationReason: r.cancellation_reason,
    cancelledBy: r.cancelled_by,
    cancelledByName: r.cancelled_by_name,
    cancelledAt: r.cancelled_at,
    notes: r.notes,
    items: itemsByOrder.get(r.id) || [],
    payments: paymentsByOrder.get(r.id) || [],
    refunds: refundsByOrder.get(r.id) || [],
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  }));

  db.expenses = expenses.map((r) => ({
    id: r.id,
    category: r.category,
    amount: Number(r.amount || 0),
    expenseDate: r.expense_date,
    description: r.description,
    paymentMethod: r.payment_method,
    addedBy: r.added_by,
    addedByName: r.added_by_name,
    orderId: r.order_id,
    batchId: r.batch_id,
    notes: r.notes,
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  }));

  db.inventoryTransactions = inventoryTransactions.map((r) => ({
    id: r.id,
    productId: r.product_id,
    variantId: r.variant_id,
    productName: r.product_name,
    variantLabel: r.variant_label,
    transactionType: r.transaction_type,
    quantity: Number(r.quantity || 0),
    referenceType: r.reference_type,
    referenceId: r.reference_id,
    staffId: r.staff_id,
    staffName: r.staff_name,
    notes: r.notes,
    createdAt: r.created_at,
  }));

  db.auditLogs = auditLogs.map((r) => ({
    id: r.id,
    userId: r.user_id,
    userName: r.user_name,
    action: r.action,
    entityType: r.entity_type,
    entityId: r.entity_id,
    details: r.details,
    createdAt: r.created_at,
  }));

  db.dismissedNotifications = dismissedNotifications.map((r) => r.id);

  db.settings = {};

  for (const row of settings) {
    db.settings[row.setting_key] = normalizeJson(row.setting_value, row.setting_value);
  }

  return db;
}

async function saveDb(db) {
  const saveStartedAt = Date.now();
  const client = await getPool().connect();

  // Batch size keeps PostgreSQL queries reasonably small.
  const CHUNK_SIZE = 500;

  const bulkUpsert = async (
    table,
    columns,
    rows,
    conflictColumn,
    updateColumns
  ) => {
    if (!rows.length) return;

    for (let start = 0; start < rows.length; start += CHUNK_SIZE) {
      const chunk = rows.slice(start, start + CHUNK_SIZE);

      const values = [];
      const placeholders = chunk.map((row, rowIndex) => {
        const rowPlaceholders = row.map((value, columnIndex) => {
          values.push(value);
          return `$${rowIndex * columns.length + columnIndex + 1}`;
        });

        return `(${rowPlaceholders.join(",")})`;
      });

      const updates = updateColumns
        .map((column) => `${column} = EXCLUDED.${column}`)
        .join(",\n");

      await client.query(
        `
        INSERT INTO ${table} (
          ${columns.join(", ")}
        )
        VALUES
          ${placeholders.join(",\n")}
        ON CONFLICT (${conflictColumn}) DO UPDATE SET
          ${updates}
        `,
        values
      );
    }
  };

  try {
    await client.query("BEGIN");

    // =========================================
    // USERS
    // =========================================

    const users = (db.users || []).map((user) => [
      user.id,
      user.name,
      user.email,
      user.passwordHash,
      user.role || "Staff",
      user.active === false ? "inactive" : "active",
      JSON.stringify(user.permissions || {}),
      user.createdAt || new Date(),
      user.updatedAt || new Date(),
    ]);

    await bulkUpsert(
      "users",
      [
        "id",
        "name",
        "email",
        "password_hash",
        "role",
        "status",
        "permissions",
        "created_at",
        "updated_at",
      ],
      users,
      "id",
      [
        "name",
        "email",
        "password_hash",
        "role",
        "status",
        "permissions",
        "updated_at",
      ]
    );

    // =========================================
    // CUSTOMERS
    // =========================================

    const customers = (db.customers || []).map((customer) => [
      customer.id,
      customer.customerCode,
      customer.name,
      customer.phone,
      nullable(customer.email),
      nullable(customer.contact),
      nullable(customer.address),
      nullable(customer.township),
      customer.deliveryMethod || "Deli",
      nullable(customer.notes),
      nullable(customer.customerVisibleNotes),
      nullable(customer.internalNotes),
      JSON.stringify(customer.tags || []),
      customer.createdAt || new Date(),
      customer.updatedAt || new Date(),
    ]);

    await bulkUpsert(
      "customers",
      [
        "id",
        "customer_code",
        "name",
        "phone",
        "email",
        "contact",
        "address",
        "township",
        "delivery_method",
        "notes",
        "customer_visible_notes",
        "internal_notes",
        "tags",
        "created_at",
        "updated_at",
      ],
      customers,
      "id",
      [
        "customer_code",
        "name",
        "phone",
        "email",
        "contact",
        "address",
        "township",
        "delivery_method",
        "notes",
        "customer_visible_notes",
        "internal_notes",
        "tags",
        "updated_at",
      ]
    );

    // =========================================
    // PRODUCTS
    // =========================================

    const products = (db.products || []).map((product) => [
      product.id,
      product.productCode,
      product.sku,
      product.name,
      nullable(product.description),
      nullable(product.category),
      nullable(product.supplier),
      product.productType || "Preorder",
      Number(product.costPrice || 0),
      Number(product.sellingPrice || 0),
      Number(product.discountPrice || 0),
      nullable(product.supplierLink),
      nullable(product.supplierProductCode),
      Number(product.supplierPrice || 0),
      Number(product.estimatedProductCost || 0),
      nullable(product.defaultWaitingTime),
      Number(product.defaultCargoCost || 0),
      nullable(product.customerDescription),
      nullable(product.notes),
      nullable(product.internalNotes),
      JSON.stringify(product.availableSizes || []),
      JSON.stringify(product.availableColors || []),
      JSON.stringify(product.images || []),
      product.status || "active",
      product.createdAt || new Date(),
      product.updatedAt || new Date(),
    ]);

    await bulkUpsert(
      "products",
      [
        "id",
        "product_code",
        "sku",
        "name",
        "description",
        "category",
        "supplier",
        "product_type",
        "cost_price",
        "selling_price",
        "discount_price",
        "supplier_link",
        "supplier_product_code",
        "supplier_price",
        "estimated_product_cost",
        "default_waiting_time",
        "default_cargo_cost",
        "customer_description",
        "notes",
        "internal_notes",
        "available_sizes",
        "available_colors",
        "images",
        "status",
        "created_at",
        "updated_at",
      ],
      products,
      "id",
      [
        "product_code",
        "sku",
        "name",
        "description",
        "category",
        "supplier",
        "product_type",
        "cost_price",
        "selling_price",
        "discount_price",
        "supplier_link",
        "supplier_product_code",
        "supplier_price",
        "estimated_product_cost",
        "default_waiting_time",
        "default_cargo_cost",
        "customer_description",
        "notes",
        "internal_notes",
        "available_sizes",
        "available_colors",
        "images",
        "status",
        "updated_at",
      ]
    );

    // =========================================
    // PRODUCT VARIANTS
    // =========================================

    const variants = [];

    for (const product of db.products || []) {
      for (const variant of product.variants || []) {
        variants.push([
          variant.id,
          product.id,
          nullable(variant.sku),
          variant.size || "Free",
          variant.color || "Default",
          Number(variant.costPrice || 0),
          Number(variant.sellingPrice || 0),
          Number(variant.stockQuantity || 0),
          Number(variant.reservedQuantity || 0),
          Number(variant.soldQuantity || 0),
          Number(variant.returnedQuantity || 0),
          Number(variant.damagedQuantity || 0),
          Number(variant.lowStockThreshold || 0),
          variant.status || "active",
          variant.createdAt || new Date(),
          variant.updatedAt || new Date(),
        ]);
      }
    }

    await bulkUpsert(
      "product_variants",
      [
        "id",
        "product_id",
        "sku",
        "size",
        "color",
        "cost_price",
        "selling_price",
        "stock_quantity",
        "reserved_quantity",
        "sold_quantity",
        "returned_quantity",
        "damaged_quantity",
        "low_stock_threshold",
        "status",
        "created_at",
        "updated_at",
      ],
      variants,
      "id",
      [
        "product_id",
        "sku",
        "size",
        "color",
        "cost_price",
        "selling_price",
        "stock_quantity",
        "reserved_quantity",
        "sold_quantity",
        "returned_quantity",
        "damaged_quantity",
        "low_stock_threshold",
        "status",
        "updated_at",
      ]
    );

    // =========================================
    // PRODUCT COST HISTORY
    // =========================================

    const costHistory = [];

    for (const product of db.products || []) {
      for (const history of product.costHistory || []) {
        costHistory.push([
          history.id,
          product.id,
          Number(history.cost || 0),
          history.date,
          nullable(history.note),
          history.createdAt || new Date(),
        ]);
      }
    }

    await bulkUpsert(
      "product_cost_history",
      [
        "id",
        "product_id",
        "cost",
        "cost_date",
        "note",
        "created_at",
      ],
      costHistory,
      "id",
      [
        "product_id",
        "cost",
        "cost_date",
        "note",
      ]
    );

    // =========================================
    // ORDERS
    // =========================================

    const orders = (db.orders || []).map((order) => [
      order.id,
      order.orderNumber,
      order.customerId,
      nullable(order.createdBy),
      order.orderType,
      order.orderDate,
      order.status,
      nullable(order.preorderStatus),
      nullable(order.packingStatus),
      nullable(order.deliveryStatus),
      nullable(order.deliveryMethod),
      nullable(order.trackingNumber),
      nullable(order.waitingTime),
      nullable(order.expectedArrival),
      nullable(order.batchId),
      Boolean(order.customerNotified),
      nullable(order.customerNotes),
      nullable(order.internalNotes),
      order.stockState || "draft",
      Number(order.subtotal || 0),
      Number(order.discount || 0),
      Number(order.deliveryFee || 0),
      Number(order.shopDeliveryCost || 0),
      Number(order.allocatedExpense || 0),
      Number(order.total || 0),
      Number(order.paidAmount || 0),
      Number(order.refundedAmount || 0),
      Number(order.finalPaidAmount || 0),
      Number(order.balance || 0),
      Number(order.requiredDeposit || 0),
      Number(order.productCost || 0),
      Number(order.cargoCost || 0),
      Number(order.netProfit || 0),
      nullable(order.paymentStatus),
      nullable(order.packedBy),
      nullable(order.packedByName),
      nullable(order.packedAt),
      nullable(order.cancellationReason),
      nullable(order.cancelledBy),
      nullable(order.cancelledByName),
      nullable(order.cancelledAt),
      nullable(order.notes),
      order.createdAt || new Date(),
      order.updatedAt || new Date(),
    ]);

    await bulkUpsert(
      "orders",
      [
        "id",
        "order_number",
        "customer_id",
        "created_by",
        "order_type",
        "order_date",
        "status",
        "preorder_status",
        "packing_status",
        "delivery_status",
        "delivery_method",
        "tracking_number",
        "waiting_time",
        "expected_arrival",
        "batch_id",
        "customer_notified",
        "customer_notes",
        "internal_notes",
        "stock_state",
        "subtotal",
        "discount",
        "delivery_fee",
        "shop_delivery_cost",
        "allocated_expense",
        "total",
        "paid_amount",
        "refunded_amount",
        "final_paid_amount",
        "balance",
        "required_deposit",
        "product_cost",
        "cargo_cost",
        "net_profit",
        "payment_status",
        "packed_by",
        "packed_by_name",
        "packed_at",
        "cancellation_reason",
        "cancelled_by",
        "cancelled_by_name",
        "cancelled_at",
        "notes",
        "created_at",
        "updated_at",
      ],
      orders,
      "id",
      [
        "order_number",
        "customer_id",
        "created_by",
        "order_type",
        "order_date",
        "status",
        "preorder_status",
        "packing_status",
        "delivery_status",
        "delivery_method",
        "tracking_number",
        "waiting_time",
        "expected_arrival",
        "batch_id",
        "customer_notified",
        "customer_notes",
        "internal_notes",
        "stock_state",
        "subtotal",
        "discount",
        "delivery_fee",
        "shop_delivery_cost",
        "allocated_expense",
        "total",
        "paid_amount",
        "refunded_amount",
        "final_paid_amount",
        "balance",
        "required_deposit",
        "product_cost",
        "cargo_cost",
        "net_profit",
        "payment_status",
        "packed_by",
        "packed_by_name",
        "packed_at",
        "cancellation_reason",
        "cancelled_by",
        "cancelled_by_name",
        "cancelled_at",
        "notes",
        "updated_at",
      ]
    );

    // =========================================
    // ORDER ITEMS
    // =========================================

    const orderItems = [];

    for (const order of db.orders || []) {
      for (const item of order.items || []) {
        orderItems.push([
          item.id,
          order.id,
          item.productId,
          item.variantId,
          item.productName,
          nullable(item.sku),
          nullable(item.size),
          nullable(item.color),
          Number(item.quantity || 0),
          Number(item.unitPrice || 0),
          Number(item.purchaseCost || 0),
          Number(item.cargoCost || 0),
          Number(item.discount || 0),
          Number(item.subtotal || 0),
          nullable(item.supplierStatus),
          nullable(item.cargoStatus),
          nullable(item.arrivalStatus),
          nullable(item.expectedArrival),
          nullable(item.batchId),
          Boolean(item.customerNotified),
          item.createdAt || new Date(),
        ]);
      }
    }

    await bulkUpsert(
      "order_items",
      [
        "id",
        "order_id",
        "product_id",
        "variant_id",
        "product_name_snapshot",
        "sku",
        "size",
        "color",
        "quantity",
        "unit_price",
        "cost_price",
        "cargo_cost",
        "discount",
        "subtotal",
        "supplier_status",
        "cargo_status",
        "arrival_status",
        "expected_arrival",
        "batch_id",
        "customer_notified",
        "created_at",
      ],
      orderItems,
      "id",
      [
        "order_id",
        "product_id",
        "variant_id",
        "product_name_snapshot",
        "sku",
        "size",
        "color",
        "quantity",
        "unit_price",
        "cost_price",
        "cargo_cost",
        "discount",
        "subtotal",
        "supplier_status",
        "cargo_status",
        "arrival_status",
        "expected_arrival",
        "batch_id",
        "customer_notified",
      ]
    );

    // =========================================
    // PAYMENTS
    // =========================================

    const payments = (db.payments || []).map((payment) => [
      payment.id,
      payment.orderId,
      nullable(payment.customerId),
      Number(payment.amount || 0),
      payment.paymentMethod || "KPay",
      payment.paymentType || "payment",
      payment.paymentDate,
      nullable(payment.reference),
      nullable(payment.receivedBy),
      nullable(payment.receivedByName),
      nullable(payment.notes),
      payment.createdAt || new Date(),
    ]);

    await bulkUpsert(
      "payments",
      [
        "id",
        "order_id",
        "customer_id",
        "amount",
        "payment_method",
        "payment_type",
        "payment_date",
        "reference",
        "received_by",
        "received_by_name",
        "notes",
        "created_at",
      ],
      payments,
      "id",
      [
        "order_id",
        "customer_id",
        "amount",
        "payment_method",
        "payment_type",
        "payment_date",
        "reference",
        "received_by",
        "received_by_name",
        "notes",
      ]
    );

    // =========================================
    // REFUNDS
    // =========================================

    const refunds = (db.refunds || []).map((refund) => [
      refund.id,
      refund.orderId,
      nullable(refund.customerId),
      Number(refund.amount || 0),
      refund.method || "KPay",
      nullable(refund.reason),
      refund.refundDate,
      nullable(refund.processedBy),
      nullable(refund.processedByName),
      refund.createdAt || new Date(),
    ]);

    await bulkUpsert(
      "refunds",
      [
        "id",
        "order_id",
        "customer_id",
        "amount",
        "method",
        "reason",
        "refund_date",
        "processed_by",
        "processed_by_name",
        "created_at",
      ],
      refunds,
      "id",
      [
        "order_id",
        "customer_id",
        "amount",
        "method",
        "reason",
        "refund_date",
        "processed_by",
        "processed_by_name",
      ]
    );

    // =========================================
    // RETURNS
    // =========================================

    const returns = (db.returns || []).map((ret) => [
      ret.id,
      ret.orderId,
      nullable(ret.customerId),
      nullable(ret.reason),
      ret.status || "Processed",
      nullable(ret.processedBy),
      nullable(ret.processedByName),
      ret.returnDate,
      ret.createdAt || new Date(),
    ]);

    await bulkUpsert(
      "returns",
      [
        "id",
        "order_id",
        "customer_id",
        "reason",
        "status",
        "processed_by",
        "processed_by_name",
        "return_date",
        "created_at",
      ],
      returns,
      "id",
      [
        "order_id",
        "customer_id",
        "reason",
        "status",
        "processed_by",
        "processed_by_name",
        "return_date",
      ]
    );

    // =========================================
    // RETURN ITEMS
    // =========================================

    const returnItems = [];

    for (const ret of db.returns || []) {
      for (const item of ret.items || []) {
        returnItems.push([
          item.id,
          ret.id,
          nullable(item.orderItemId),
          nullable(item.productName),
          nullable(item.variantId),
          nullable(item.color),
          nullable(item.size),
          Number(item.quantity || 0),
          item.condition || "Resellable",
          item.createdAt || new Date(),
        ]);
      }
    }

    await bulkUpsert(
      "return_items",
      [
        "id",
        "return_id",
        "order_item_id",
        "product_name",
        "variant_id",
        "color",
        "size",
        "quantity",
        "condition",
        "created_at",
      ],
      returnItems,
      "id",
      [
        "return_id",
        "order_item_id",
        "product_name",
        "variant_id",
        "color",
        "size",
        "quantity",
        "condition",
      ]
    );

    // =========================================
    // EXPENSES
    // =========================================

    const expenses = (db.expenses || []).map((expense) => [
      expense.id,
      expense.category || "Other",
      Number(expense.amount || 0),
      expense.expenseDate,
      nullable(expense.description),
      nullable(expense.paymentMethod),
      nullable(expense.addedBy),
      nullable(expense.addedByName),
      nullable(expense.orderId),
      nullable(expense.batchId),
      nullable(expense.notes),
      expense.createdAt || new Date(),
      expense.updatedAt || new Date(),
    ]);

    await bulkUpsert(
      "expenses",
      [
        "id",
        "category",
        "amount",
        "expense_date",
        "description",
        "payment_method",
        "added_by",
        "added_by_name",
        "order_id",
        "batch_id",
        "notes",
        "created_at",
        "updated_at",
      ],
      expenses,
      "id",
      [
        "category",
        "amount",
        "expense_date",
        "description",
        "payment_method",
        "added_by",
        "added_by_name",
        "order_id",
        "batch_id",
        "notes",
        "updated_at",
      ]
    );

    // =========================================
    // INVENTORY TRANSACTIONS
    // =========================================

    const inventoryTransactions = (db.inventoryTransactions || []).map(
      (tx) => [
        tx.id,
        nullable(tx.productId),
        nullable(tx.variantId),
        nullable(tx.productName),
        nullable(tx.variantLabel),
        tx.transactionType,
        Number(tx.quantity || 0),
        nullable(tx.referenceType),
        nullable(tx.referenceId),
        nullable(tx.staffId),
        nullable(tx.staffName),
        nullable(tx.notes),
        tx.createdAt || new Date(),
      ]
    );

    await bulkUpsert(
      "inventory_transactions",
      [
        "id",
        "product_id",
        "variant_id",
        "product_name",
        "variant_label",
        "transaction_type",
        "quantity",
        "reference_type",
        "reference_id",
        "staff_id",
        "staff_name",
        "notes",
        "created_at",
      ],
      inventoryTransactions,
      "id",
      [
        "product_id",
        "variant_id",
        "product_name",
        "variant_label",
        "transaction_type",
        "quantity",
        "reference_type",
        "reference_id",
        "staff_id",
        "staff_name",
        "notes",
      ]
    );

    // =========================================
    // AUDIT LOGS
    // =========================================

    const auditLogs = (db.auditLogs || []).map((log) => [
      log.id,
      nullable(log.userId),
      nullable(log.userName),
      log.action,
      nullable(log.entityType),
      nullable(log.entityId),
      nullable(log.details),
      log.createdAt || new Date(),
    ]);

    await bulkUpsert(
      "audit_logs",
      [
        "id",
        "user_id",
        "user_name",
        "action",
        "entity_type",
        "entity_id",
        "details",
        "created_at",
      ],
      auditLogs,
      "id",
      [
        "user_id",
        "user_name",
        "action",
        "entity_type",
        "entity_id",
        "details",
      ]
    );

    // =========================================
    // DISMISSED NOTIFICATIONS
    // =========================================

    const dismissedNotifications = (db.dismissedNotifications || []).map(
      (id) => [id]
    );

    await bulkUpsert(
      "dismissed_notifications",
      ["id"],
      dismissedNotifications,
      "id",
      []
    );

    // =========================================
    // SETTINGS
    // =========================================

    const settings = Object.entries(db.settings || {}).map(
      ([key, value]) => [
        key,
        JSON.stringify(value),
      ]
    );

    await bulkUpsert(
      "settings",
      [
        "setting_key",
        "setting_value",
      ],
      settings,
      "setting_key",
      [
        "setting_value",
      ]
    );

    // =========================================
    // COMMIT
    // =========================================

    await client.query("COMMIT");

    console.log(
      `PostgreSQL saveDb(): ` +
      `${db.orders?.length || 0} orders, ` +
      `${(db.orders || []).reduce(
        (n, o) => n + (o.items || []).length,
        0
      )} items, ` +
      `${db.payments?.length || 0} payments saved ` +
      `(${Date.now() - saveStartedAt}ms)`
    );
  } catch (error) {
    await client.query("ROLLBACK");
    console.error("PostgreSQL saveDb() failed:", error);
    throw error;
  } finally {
    client.release();
  }
}

async function ping() {
  const { rows } = await getPool().query(
    "SELECT version() AS version"
  );

  return rows[0];
}

async function tableCounts() {
  const tables = [
    "audit_logs",
    "cargo_batches",
    "cargo_items",
    "customers",
    "dismissed_notifications",
    "expenses",
    "inventory_transactions",
    "order_items",
    "order_status_history",
    "order_timeline",
    "orders",
    "payments",
    "product_cost_history",
    "product_variants",
    "products",
    "refunds",
    "return_items",
    "returns",
    "schema_migrations",
    "settings",
    "suppliers",
    "users",
  ];

  const result = {};

  for (const table of tables) {
    const { rows } = await getPool().query(
      `SELECT COUNT(*)::int AS count FROM ${table}`
    );

    result[table] = rows[0].count;
  }

  return result;
}

async function closePool() {
  if (pool) {
    await pool.end();
    pool = null;
  }
}

module.exports = {
  migrate,
  loadDb,
  saveDb,
  ping,
  tableCounts,
  closePool,
};
