require("dotenv").config();

const fs = require("fs");
const path = require("path");
const { Pool } = require("pg");

let pool;

function getPool() {
  if (pool) return pool;

  if (!process.env.DATABASE_URL) {
    throw new Error("DATABASE_URL is not set");
  }

  pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false },
  });

  return pool;
}

function normalizeJson(value, fallback = null) {
  if (value === undefined || value === null) return fallback;
  if (typeof value === "string") {
    try {
      return JSON.parse(value);
    } catch {
      return fallback;
    }
  }
  return value;
}

function nullable(value) {
  return value === "" || value === undefined ? null : value;
}

async function migrate() {
  const db = getPool();

  await db.query(`
    CREATE TABLE IF NOT EXISTS schema_migrations (
      id integer generated by default as identity primary key,
      filename varchar(191) not null unique,
      applied_at timestamptz not null default now()
    )
  `);

  const schemaPath = path.join(
    __dirname,
    "..",
    "database",
    "supabase",
    "001_schema.sql"
  );

  if (!fs.existsSync(schemaPath)) {
    throw new Error(`PostgreSQL schema not found: ${schemaPath}`);
  }

  const schema = fs.readFileSync(schemaPath, "utf8");

  await db.query(schema);

  return true;
}

async function queryRows(table) {
  const { rows } = await getPool().query(`SELECT * FROM ${table}`);
  return rows;
}

async function loadDb(createEmptyDb) {
  const db = createEmptyDb();

  const [
    users,
    customers,
    products,
    variants,
    costHistory,
    suppliers,
    cargoBatches,
    orders,
    orderItems,
    timelines,
    statusHistory,
    payments,
    refunds,
    returns,
    returnItems,
    cargoItems,
    expenses,
    inventoryTransactions,
    auditLogs,
    dismissedNotifications,
    settings,
  ] = await Promise.all([
    queryRows("users"),
    queryRows("customers"),
    queryRows("products"),
    queryRows("product_variants"),
    queryRows("product_cost_history"),
    queryRows("suppliers"),
    queryRows("cargo_batches"),
    queryRows("orders"),
    queryRows("order_items"),
    queryRows("order_timeline"),
    queryRows("order_status_history"),
    queryRows("payments"),
    queryRows("refunds"),
    queryRows("returns"),
    queryRows("return_items"),
    queryRows("cargo_items"),
    queryRows("expenses"),
    queryRows("inventory_transactions"),
    queryRows("audit_logs"),
    queryRows("dismissed_notifications"),
    queryRows("settings"),
  ]);

  db.users = users.map((r) => ({
    id: r.id,
    name: r.name,
    email: r.email,
    passwordHash: r.password_hash,
    role: r.role,
    active: r.status === "active",
    permissions: normalizeJson(r.permissions, {}),
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  }));

  db.customers = customers.map((r) => ({
    id: r.id,
    customerCode: r.customer_code,
    name: r.name,
    phone: r.phone,
    email: r.email,
    contact: r.contact,
    address: r.address,
    township: r.township,
    deliveryMethod: r.delivery_method || "Deli",
    notes: r.notes,
    customerVisibleNotes: r.customer_visible_notes,
    internalNotes: r.internal_notes,
    tags: normalizeJson(r.tags, []),
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  }));

  const costByProduct = new Map();

  for (const row of costHistory) {
    if (!costByProduct.has(row.product_id)) {
      costByProduct.set(row.product_id, []);
    }

    costByProduct.get(row.product_id).push({
      id: row.id,
      cost: Number(row.cost || 0),
      date: row.cost_date,
      note: row.note,
      createdAt: row.created_at,
    });
  }

  const variantsByProduct = new Map();

  for (const row of variants) {
    if (!variantsByProduct.has(row.product_id)) {
      variantsByProduct.set(row.product_id, []);
    }

    variantsByProduct.get(row.product_id).push({
      id: row.id,
      productId: row.product_id,
      sku: row.sku,
      size: row.size,
      color: row.color,
      costPrice: Number(row.cost_price || 0),
      sellingPrice: Number(row.selling_price || 0),
      stockQuantity: Number(row.stock_quantity || 0),
      reservedQuantity: Number(row.reserved_quantity || 0),
      soldQuantity: Number(row.sold_quantity || 0),
      returnedQuantity: Number(row.returned_quantity || 0),
      damagedQuantity: Number(row.damaged_quantity || 0),
      lowStockThreshold: Number(row.low_stock_threshold || 0),
      status: row.status,
      createdAt: row.created_at,
      updatedAt: row.updated_at,
    });
  }

  db.products = products.map((r) => ({
    id: r.id,
    productCode: r.product_code,
    sku: r.sku,
    name: r.name,
    description: r.description,
    category: r.category,
    supplier: r.supplier,
    productType: r.product_type,
    costPrice: Number(r.cost_price || 0),
    sellingPrice: Number(r.selling_price || 0),
    discountPrice: Number(r.discount_price || 0),
    supplierLink: r.supplier_link,
    supplierProductCode: r.supplier_product_code,
    supplierPrice: Number(r.supplier_price || 0),
    estimatedProductCost: Number(r.estimated_product_cost || 0),
    defaultWaitingTime: r.default_waiting_time,
    defaultCargoCost: Number(r.default_cargo_cost || 0),
    customerDescription: r.customer_description,
    notes: r.notes,
    internalNotes: r.internal_notes,
    availableSizes: normalizeJson(r.available_sizes, []),
    availableColors: normalizeJson(r.available_colors, []),
    images: normalizeJson(r.images, []),
    status: r.status,
    variants: variantsByProduct.get(r.id) || [],
    costHistory: costByProduct.get(r.id) || [],
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  }));

  db.suppliers = suppliers.map((r) => ({
    id: r.id,
    name: r.name,
    platform: r.platform,
    supplierLink: r.supplier_link,
    contact: r.contact,
    note: r.note,
    productCost: Number(r.product_cost || 0),
    supplierStatus: r.supplier_status,
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  }));

  const cargoItemsByBatch = new Map();

  for (const row of cargoItems) {
    if (!cargoItemsByBatch.has(row.cargo_batch_id)) {
      cargoItemsByBatch.set(row.cargo_batch_id, []);
    }

    cargoItemsByBatch.get(row.cargo_batch_id).push(row);
  }

  db.cargoBatches = cargoBatches.map((r) => {
    const items = cargoItemsByBatch.get(r.id) || [];

    return {
      id: r.id,
      batchId: r.batch_id,
      route: r.route,
      cargoFee: Number(r.cargo_fee || 0),
      chinaMuseCargoFee: Number(r.china_muse_cargo_fee || 0),
      museYangonCargoFee: Number(r.muse_yangon_cargo_fee || 0),
      otherExpenses: Number(r.other_expenses || 0),
      status: r.status,
      batchDate: r.batch_date,
      arrivalDate: r.arrival_date,
      notes: r.notes,
      orderIds: [...new Set(items.map((x) => x.order_id).filter(Boolean))],
      productIds: [...new Set(items.map((x) => x.product_id).filter(Boolean))],
      createdAt: r.created_at,
      updatedAt: r.updated_at,
    };
  });

  const itemsByOrder = new Map();

  for (const row of orderItems) {
    if (!itemsByOrder.has(row.order_id)) {
      itemsByOrder.set(row.order_id, []);
    }

    itemsByOrder.get(row.order_id).push({
      id: row.id,
      productId: row.product_id,
      variantId: row.variant_id,
      productName: row.product_name_snapshot,
      sku: row.sku,
      size: row.size,
      color: row.color,
      quantity: Number(row.quantity || 0),
      unitPrice: Number(row.unit_price || 0),
      purchaseCost: Number(row.cost_price || 0),
      cargoCost: Number(row.cargo_cost || 0),
      discount: Number(row.discount || 0),
      subtotal: Number(row.subtotal || 0),
      supplierStatus: row.supplier_status,
      cargoStatus: row.cargo_status,
      arrivalStatus: row.arrival_status,
      expectedArrival: row.expected_arrival,
      batchId: row.batch_id,
      customerNotified: row.customer_notified,
      createdAt: row.created_at,
    });
  }

  const paymentsByOrder = new Map();

  for (const row of payments) {
    if (!paymentsByOrder.has(row.order_id)) {
      paymentsByOrder.set(row.order_id, []);
    }

    paymentsByOrder.get(row.order_id).push({
      id: row.id,
      orderId: row.order_id,
      customerId: row.customer_id,
      amount: Number(row.amount || 0),
      paymentMethod: row.payment_method,
      paymentType: row.payment_type,
      paymentDate: row.payment_date,
      reference: row.reference,
      receivedBy: row.received_by,
      receivedByName: row.received_by_name,
      notes: row.notes,
      createdAt: row.created_at,
    });
  }

  const refundsByOrder = new Map();

  for (const row of refunds) {
    if (!refundsByOrder.has(row.order_id)) {
      refundsByOrder.set(row.order_id, []);
    }

    refundsByOrder.get(row.order_id).push({
      id: row.id,
      orderId: row.order_id,
      customerId: row.customer_id,
      amount: Number(row.amount || 0),
      method: row.method,
      reason: row.reason,
      refundDate: row.refund_date,
      processedBy: row.processed_by,
      processedByName: row.processed_by_name,
      createdAt: row.created_at,
    });
  }

  db.orders = orders.map((r) => ({
    id: r.id,
    orderNumber: r.order_number,
    customerId: r.customer_id,
    createdBy: r.created_by,
    orderType: r.order_type,
    orderDate: r.order_date,
    status: r.status,
    preorderStatus: r.preorder_status,
    packingStatus: r.packing_status,
    deliveryStatus: r.delivery_status,
    deliveryMethod: r.delivery_method,
    trackingNumber: r.tracking_number,
    waitingTime: r.waiting_time,
    expectedArrival: r.expected_arrival,
    batchId: r.batch_id,
    customerNotified: r.customer_notified,
    customerNotes: r.customer_notes,
    internalNotes: r.internal_notes,
    stockState: r.stock_state,
    subtotal: Number(r.subtotal || 0),
    discount: Number(r.discount || 0),
    deliveryFee: Number(r.delivery_fee || 0),
    shopDeliveryCost: Number(r.shop_delivery_cost || 0),
    allocatedExpense: Number(r.allocated_expense || 0),
    total: Number(r.total || 0),
    paidAmount: Number(r.paid_amount || 0),
    refundedAmount: Number(r.refunded_amount || 0),
    finalPaidAmount: Number(r.final_paid_amount || 0),
    balance: Number(r.balance || 0),
    requiredDeposit: Number(r.required_deposit || 0),
    productCost: Number(r.product_cost || 0),
    cargoCost: Number(r.cargo_cost || 0),
    netProfit: Number(r.net_profit || 0),
    paymentStatus: r.payment_status,
    packedBy: r.packed_by,
    packedByName: r.packed_by_name,
    packedAt: r.packed_at,
    cancellationReason: r.cancellation_reason,
    cancelledBy: r.cancelled_by,
    cancelledByName: r.cancelled_by_name,
    cancelledAt: r.cancelled_at,
    notes: r.notes,
    items: itemsByOrder.get(r.id) || [],
    payments: paymentsByOrder.get(r.id) || [],
    refunds: refundsByOrder.get(r.id) || [],
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  }));

  db.expenses = expenses.map((r) => ({
    id: r.id,
    category: r.category,
    amount: Number(r.amount || 0),
    expenseDate: r.expense_date,
    description: r.description,
    paymentMethod: r.payment_method,
    addedBy: r.added_by,
    addedByName: r.added_by_name,
    orderId: r.order_id,
    batchId: r.batch_id,
    notes: r.notes,
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  }));

  db.inventoryTransactions = inventoryTransactions.map((r) => ({
    id: r.id,
    productId: r.product_id,
    variantId: r.variant_id,
    productName: r.product_name,
    variantLabel: r.variant_label,
    transactionType: r.transaction_type,
    quantity: Number(r.quantity || 0),
    referenceType: r.reference_type,
    referenceId: r.reference_id,
    staffId: r.staff_id,
    staffName: r.staff_name,
    notes: r.notes,
    createdAt: r.created_at,
  }));

  db.auditLogs = auditLogs.map((r) => ({
    id: r.id,
    userId: r.user_id,
    userName: r.user_name,
    action: r.action,
    entityType: r.entity_type,
    entityId: r.entity_id,
    details: r.details,
    createdAt: r.created_at,
  }));

  db.dismissedNotifications = dismissedNotifications.map((r) => r.id);

  db.settings = {};

  for (const row of settings) {
    db.settings[row.setting_key] = normalizeJson(row.setting_value, row.setting_value);
  }

  return db;
}

async function saveDb() {
  throw new Error(
    "PostgreSQL saveDb() is not enabled yet. The first step is read-only Neon verification."
  );
}

async function ping() {
  const { rows } = await getPool().query(
    "SELECT version() AS version"
  );

  return rows[0];
}

async function tableCounts() {
  const tables = [
    "audit_logs",
    "cargo_batches",
    "cargo_items",
    "customers",
    "dismissed_notifications",
    "expenses",
    "inventory_transactions",
    "order_items",
    "order_status_history",
    "order_timeline",
    "orders",
    "payments",
    "product_cost_history",
    "product_variants",
    "products",
    "refunds",
    "return_items",
    "returns",
    "schema_migrations",
    "settings",
    "suppliers",
    "users",
  ];

  const result = {};

  for (const table of tables) {
    const { rows } = await getPool().query(
      `SELECT COUNT(*)::int AS count FROM ${table}`
    );

    result[table] = rows[0].count;
  }

  return result;
}

async function closePool() {
  if (pool) {
    await pool.end();
    pool = null;
  }
}

module.exports = {
  migrate,
  loadDb,
  saveDb,
  ping,
  tableCounts,
  closePool,
};
